package com.jeffryProject.dao;

import com.jeffryProject.entity.Articles;

public interface ArticlesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_article
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int deleteByPrimaryKey(Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_article
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int insert(Articles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_article
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int insertSelective(Articles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_article
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    Articles selectByPrimaryKey(Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_article
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int updateByPrimaryKeySelective(Articles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_article
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Articles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_article
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int updateByPrimaryKey(Articles record);
}