package com.jeffryProject.dao;

import com.jeffryProject.entity.File;

public interface FileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_file
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int deleteByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_file
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int insert(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_file
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int insertSelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_file
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    File selectByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_file
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int updateByPrimaryKeySelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_file
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int updateByPrimaryKey(File record);
}