package com.jeffryProject.dao;

import com.jeffryProject.entity.Psw;

public interface PswMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_psw
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_psw
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    int insert(Psw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_psw
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    int insertSelective(Psw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_psw
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    Psw selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_psw
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    int updateByPrimaryKeySelective(Psw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_psw
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    int updateByPrimaryKey(Psw record);

    /**
     * 获取用户密码
     * @param uid
     * @return
     */
    Psw selectUserPsw(int uid);
}