package com.jeffryProject.dao;

import com.jeffryProject.entity.Role;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_role
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_role
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_role
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_role
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    Role selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_role
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_role
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int updateByPrimaryKey(Role record);
}