package com.jeffryProject.dao;

import com.jeffryProject.entity.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_user
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_user
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_user
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_user
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    User selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_user
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_user
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    int updateByPrimaryKey(User record);

    /**
     * 通过uid获取用户信息
     * @param uid
     * @return
     */
    User selectUserInfo(int uid);

    /**
     * 通过用户名获取用户信息
     * @param username
     * @return
     */
    User selectUserInfoByUsername(String username);
    /**
     * 通过用户名获取用户信息
     * @param email
     * @return
     */
    User selectUserInfoByEmail(String email);
}