package com.jeffryProject.dao;

import com.jeffryProject.entity.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_user
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_user
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_user
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_user
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    User selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_user
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jeff_user
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    int updateByPrimaryKey(User record);

    /**
     * 根据uid查询用户信息
     * @param uid
     * @return
     */
    User selectUserInfo(int uid);

    /**
     * 根据用户名查询用户数据
     * @param username
     * @return
     */
    User selectUserInfoByUsername(String username);
}