package com.jeffryProject.entity;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_category.category_id
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_category.category_name
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private String categoryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_category.category_id
     *
     * @return the value of jeff_category.category_id
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_category.category_id
     *
     * @param categoryId the value for jeff_category.category_id
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_category.category_name
     *
     * @return the value of jeff_category.category_name
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_category.category_name
     *
     * @param categoryName the value for jeff_category.category_name
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }
}