package com.jeffryProject.entity;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_comment.comid
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private Integer comid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_comment.pcomid
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private Integer pcomid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_comment.comment_detial
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private String commentDetial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_comment.comm_name
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private String commName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_comment.email
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_comment.personal_url
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private String personalUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_comment.comm_time
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private Date commTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_comment.comid
     *
     * @return the value of jeff_comment.comid
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public Integer getComid() {
        return comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_comment.comid
     *
     * @param comid the value for jeff_comment.comid
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setComid(Integer comid) {
        this.comid = comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_comment.pcomid
     *
     * @return the value of jeff_comment.pcomid
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public Integer getPcomid() {
        return pcomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_comment.pcomid
     *
     * @param pcomid the value for jeff_comment.pcomid
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setPcomid(Integer pcomid) {
        this.pcomid = pcomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_comment.comment_detial
     *
     * @return the value of jeff_comment.comment_detial
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public String getCommentDetial() {
        return commentDetial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_comment.comment_detial
     *
     * @param commentDetial the value for jeff_comment.comment_detial
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setCommentDetial(String commentDetial) {
        this.commentDetial = commentDetial == null ? null : commentDetial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_comment.comm_name
     *
     * @return the value of jeff_comment.comm_name
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public String getCommName() {
        return commName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_comment.comm_name
     *
     * @param commName the value for jeff_comment.comm_name
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setCommName(String commName) {
        this.commName = commName == null ? null : commName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_comment.email
     *
     * @return the value of jeff_comment.email
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_comment.email
     *
     * @param email the value for jeff_comment.email
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_comment.personal_url
     *
     * @return the value of jeff_comment.personal_url
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public String getPersonalUrl() {
        return personalUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_comment.personal_url
     *
     * @param personalUrl the value for jeff_comment.personal_url
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setPersonalUrl(String personalUrl) {
        this.personalUrl = personalUrl == null ? null : personalUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_comment.comm_time
     *
     * @return the value of jeff_comment.comm_time
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public Date getCommTime() {
        return commTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_comment.comm_time
     *
     * @param commTime the value for jeff_comment.comm_time
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setCommTime(Date commTime) {
        this.commTime = commTime;
    }
}