package com.jeffryProject.entity;

import com.mchange.util.MEnumeration;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

public class Psw {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_psw.id
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_psw.uid
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    @NotBlank(message = "用户id不能为空")
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_psw.password
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    @NotBlank(message = "密码不能为空")
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_psw.salt
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    @NotBlank(message = "盐值不能为空")
    private String salt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_psw.id
     *
     * @return the value of jeff_psw.id
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_psw.id
     *
     * @param id the value for jeff_psw.id
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_psw.uid
     *
     * @return the value of jeff_psw.uid
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_psw.uid
     *
     * @param uid the value for jeff_psw.uid
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_psw.password
     *
     * @return the value of jeff_psw.password
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_psw.password
     *
     * @param password the value for jeff_psw.password
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_psw.salt
     *
     * @return the value of jeff_psw.salt
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_psw.salt
     *
     * @param salt the value for jeff_psw.salt
     *
     * @mbg.generated Sun Dec 22 18:54:59 CST 2019
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }
}