package com.jeffryProject.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_user.uid
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_user.username
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_user.password
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_user.salt
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_user.sex
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_user.introduction
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_user.create_time
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_user.user_icon
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private String userIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_user.wechat
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_user.email
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_user.personal_url
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private String personalUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jeff_user.role_id
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_user.uid
     *
     * @return the value of jeff_user.uid
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_user.uid
     *
     * @param uid the value for jeff_user.uid
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_user.username
     *
     * @return the value of jeff_user.username
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_user.username
     *
     * @param username the value for jeff_user.username
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_user.password
     *
     * @return the value of jeff_user.password
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_user.password
     *
     * @param password the value for jeff_user.password
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_user.salt
     *
     * @return the value of jeff_user.salt
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_user.salt
     *
     * @param salt the value for jeff_user.salt
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_user.sex
     *
     * @return the value of jeff_user.sex
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_user.sex
     *
     * @param sex the value for jeff_user.sex
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_user.introduction
     *
     * @return the value of jeff_user.introduction
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_user.introduction
     *
     * @param introduction the value for jeff_user.introduction
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_user.create_time
     *
     * @return the value of jeff_user.create_time
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_user.create_time
     *
     * @param createTime the value for jeff_user.create_time
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_user.user_icon
     *
     * @return the value of jeff_user.user_icon
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public String getUserIcon() {
        return userIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_user.user_icon
     *
     * @param userIcon the value for jeff_user.user_icon
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setUserIcon(String userIcon) {
        this.userIcon = userIcon == null ? null : userIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_user.wechat
     *
     * @return the value of jeff_user.wechat
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_user.wechat
     *
     * @param wechat the value for jeff_user.wechat
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_user.email
     *
     * @return the value of jeff_user.email
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_user.email
     *
     * @param email the value for jeff_user.email
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_user.personal_url
     *
     * @return the value of jeff_user.personal_url
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public String getPersonalUrl() {
        return personalUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_user.personal_url
     *
     * @param personalUrl the value for jeff_user.personal_url
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setPersonalUrl(String personalUrl) {
        this.personalUrl = personalUrl == null ? null : personalUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jeff_user.role_id
     *
     * @return the value of jeff_user.role_id
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jeff_user.role_id
     *
     * @param roleId the value for jeff_user.role_id
     *
     * @mbg.generated Mon Dec 16 14:36:44 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}